version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: partners-api
    ports:
      - "3000:3000"
    volumes:
      - .:/hom/node/app
      - ./dist:/hom/node/app/dist
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - partners-network

  db:
    image: postgres:13.3
    container_name: partners-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: partners
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - partners-network

networks:
  partners-network:
